export const USER_DATA = 'USER_DATA';
export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_IN_POPUP = 'LOGGED_IN_POPUP';
export const FORGOT_PASSWORD_POPUP = 'FORGOT_PASSWORD_POPUP';
export const REGISTER_POPUP = 'REGISTER_POPUP';
export const TAXI_DATA = 'TAXI_DATA';
export const BOOKING_SUMMARY_DATA = 'BOOKING_SUMMARY_DATA';
export const USER_LOCATION = 'USER_LOCATION';
export const SERVICE_SEGMENTS = 'SERVICE_SEGMENTS';
export const CONFIG_DATA = 'CONFIG_DATA';


